### ISSUE TITLE
Generated Cisco phone XML configuration files invalid

### ISSUE THREAD

**Issue by edleam** [chan-sccp/sccp_manager#58]
sccp_manager version: 14.3.0.30
7945 firmware: SCCP45.9-4-2SR3-1S

Hi,
XML files generated via sccp_manager appear to use 'on' and 'off' for options where a boolean is expected. I'm unsure if it is my specific version of firmware on the phones themselves that is unable to interpret this. 

I have tried both Cisco 7945 and Cisco 7940 IP phones. The 7945 boots but some settings on the phone (that are set by the XML file) are wrong, and logs a error interpreting the XML file. The 7940 doesn't boot at all, just keeps requesting the XML file from tftp server.

Opening the files and replacing all instances of 'on' and 'off' with 1 and 0 respectively fixes this entirely.

Every example configuration file I can find for these phones online uses 1 and 0 (including the template files in this repo for the phones I'm using, see conf/SEP0000000000.cnf.xml_796x_template)

**Comment by sq8mvy** [comment]
sccp_manager version: 14.3.0.30
7975 firmware: SCCP75.9-4-2SR4-3S

I confirm. For Cisco 7975, "on" and "off" values ​​are also generated instead of "1" and "0"

Fragment of logs from Cisco 7975:

3757: WRN 23:54:45.216449 JVM: Startup Module Loader|cip.xml.aq:  - XML Parser Warning: Unknown element 'name' in element '/device/devicePool/dateTimeSetting' (line=20)       <---- entry `<name>UTC</name>`
3758: WRN 23:54:45.218120 JVM: Startup Module Loader|cip.xml.aq:  - XML Parser Warning: Unknown element 'name' in element '/device/devicePool/srstInfo' (line=43)                     <----- entry `<name>Enable</name>`
3759: WRN 23:54:45.219768 JVM: Startup Module Loader|cip.xml.aq:  - XML Parser Warning: Unknown element 'userModifiable' in element '/device/devicePool/srstInfo' (line=44)        <--- entry `<userModifiable>false</userModifiable>`


3760: ERR 23:54:45.221678 JVM: Startup Module Loader|cip.xml.aq:  - XML Parser Exception: Element '/device/vendorConfig/settingsAccess' : Unable to parse number: value=on radix=10 (line=61)
3761: ERR 23:54:45.223411 JVM: Startup Module Loader|cip.cfg.t:? - ERROR PARSING CONFIG file:ram/SEPD824BDBBEF9E.cnf.xml
3762: NOT 23:54:45.225819 JVM: Startup Module Loader|cip.cfg.t:? - Config processConfigNoError() result code=CONFIG_FILE_BAD_FORMAT


4878: ERR 00:17:41.282570 JVM: Startup Module Loader|cip.xml.aq:  - XML Parser Exception: Element '/device/vendorConfig/settingsAccess' : Unable to parse number: value=on radix=10 (line=58)
4879: ERR 00:17:41.284397 JVM: Startup Module Loader|cip.cfg.t:? - ERROR PARSING CONFIG file:ram/SEPD824BDBBEF9E.cnf.xml
4880: NOT 00:17:41.286704 JVM: Startup Module Loader|cip.cfg.t:? - Config processConfigNoError() result code=CONFIG_FILE_BAD_FORMAT


5947: ERR 00:26:43.097036 JVM: Startup Module Loader|cip.xml.aq:  - XML Parser Exception: Element '/device/vendorConfig/videoCapability' : Unable to parse number: value=off radix=10 (line=58)
5948: ERR 00:26:43.099356 JVM: Startup Module Loader|cip.cfg.t:? - ERROR PARSING CONFIG file:ram/SEPD824BDBBEF9E.cnf.xml
5949: NOT 00:26:43.103150 JVM: Startup Module Loader|cip.cfg.t:? - Config processConfigNoError() result code=CONFIG_FILE_BAD_FORMAT


7026: ERR 00:32:04.009372 JVM: Startup Module Loader|cip.xml.aq:  - XML Parser Exception: Element '/device/vendorConfig/webAccess' : Unable to parse number: value=off radix=10 (line=59)
7027: ERR 00:32:04.011009 JVM: Startup Module Loader|cip.cfg.t:? - ERROR PARSING CONFIG file:ram/SEPD824BDBBEF9E.cnf.xml
7028: NOT 00:32:04.013349 JVM: Startup Module Loader|cip.cfg.t:? - Config processConfigNoError() result code=CONFIG_FILE_BAD_FORMAT


7928: ERR 00:40:41.418064 JVM: Startup Module Loader|cip.xml.aq:  - XML Parser Exception: Element '/device/vendorConfig/enableCdpSwPort' : Unable to parse number: value=off radix=10 (line=68)
7929: ERR 00:40:41.419721 JVM: Startup Module Loader|cip.cfg.t:? - ERROR PARSING CONFIG file:ram/SEPD824BDBBEF9E.cnf.xml

9103: ERR 01:14:51.439161 JVM: Startup Module Loader|cip.xml.aq:  - XML Parser Exception: Element '/device/vendorConfig/pcPort' : Unable to parse number: value=on radix=10 (line=77)
9104: ERR 01:14:51.440807 JVM: Startup Module Loader|cip.cfg.t:? - ERROR PARSING CONFIG file:ram/SEPD824BDBBEF9E.cnf.xml
9105: NOT 01:14:51.443140 JVM: Startup Module Loader|cip.cfg.t:? - Config processConfigNoError() result code=CONFIG_FILE_BAD_FORMAT

**Comment by steve-lad** [comment]
Thanks for reporting this. Your analysis is correct and this was fixed in v14.4.0.1
