### ISSUE TITLE
Callgroup and Pickupgroup & Namedcallgroup and Namedpickupgroup

### ISSUE THREAD

**Issue by ghost** [chan-sccp/sccp_manager#68]
FreePBX does not have the ability to edit group data. why? it's a necessary tool. please add it.

This setting does not affect anything. Can you explain why it's here? Or what does she do?
![DefPG](https://user-images.githubusercontent.com/98538479/151636796-056da237-60d3-4fd7-805d-81bc37c26cbf.PNG)

If the values are entered into the database, then for lines 108,133,134,135,136,147, Pickup and GroupPickup work fine
![2022-01-29_02-46-03](https://user-images.githubusercontent.com/98538479/151637816-56c2a3a4-d0bb-4d9f-8d8b-f34310ce4662.png)
`sccp show line 133` everything is fine, shows correctly
```
Call Group                                     : 24
Pickup Group                                   : 24
Directed Pickup                                : on
Directed Pickup Context                        :
Pickup Mode Answer                             : on
Named Call Group                               : 24
Named Pickup Group                             : 24
```

`sccp show line 160` NamedCallGroup and NamedPickupGroup show the value "NONE", although in the database (null) and accordingly all lines where in the database indicated (null) have the same group "NONE", which leads to the possibility to pickup all with this value. The solution to avoid this is to set the value of Directed Pickup to "off"
Why does "sccp show line" not output an empty value as in CallGroup or PickupGroup?
```
Call Group                                     :
Pickup Group                                   :
Directed Pickup                                : off
Directed Pickup Context                        :
Pickup Mode Answer                             : off
Named Call Group                               : NONE
Named Pickup Group                             : NONE
```

**Comment by ghost** [comment]
Postscript. The maximum number of pickup groups in asterisk is 63

**Comment by ghost** [comment]
I hope I explained it in understandable terms.

**Comment by steve-lad** [comment]
I am glad that @Nortien is contributing for you -- perhaps she should consider a donation to chan-sccp!

Your explanation is clear, and the limitations of non-named groups equally (known for a long time and largely avoided).

Pickup Group and Call Group are deprecated, not exposed,  and not supported in Sccp_manager. This (hacked) functionality will disappear in the next release because of the above highlighted and known possible exposures.

NamedCallGroups and NamedPickupGroups exist and will be more accessible in future versions
